moviesstore/cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='cart.index'),
    path('<int:id>/add/', views.add, name='cart.add'),
    path('clear/', views.clear, name='cart.clear'),
    path('purchase/', views.purchase, name='cart.purchase'),
    path('view/<int:cart_id>/', views.view_cart, name='cart.view'),
]

moviesstore/moviesstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('petitions/', include('petitions.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moviesstore/cart/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
class Order(models.Model):
    id = models.AutoField(primary_key=True)
    total = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        return str(self.id) + ' - ' + self.user.username
    
from movies.models import Movie
class Item(models.Model):
    id = models.AutoField(primary_key=True)
    price = models.IntegerField()
    quantity = models.IntegerField()
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie,on_delete=models.CASCADE)
    def __str__(self):
        return str(self.id) + ' - ' + self.movie.name

moviesstore/cart/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect
from movies.models import Movie
from cart.models import Order, Item
from .utils import calculate_cart_total
from django.contrib.auth.decorators import login_required

def index(request):
    active_cart_selection = request.session.get('active_cart', '1')
    cart_name = f'cart_{active_cart_selection}'
    cart = request.session.get(cart_name, {})
    movie_ids = list(cart.keys())

    movies_in_cart = []
    cart_total = 0
    if movie_ids:
        movies_in_cart = Movie.objects.filter(id__in=movie_ids)
        cart_total = calculate_cart_total(cart, movies_in_cart)

    template_data = {
        'title': 'Cart',
        'movies_in_cart': movies_in_cart,
        'cart_total': cart_total,
        'active_cart': int(active_cart_selection),
    }
    return render(request, 'cart/index.html', {'template_data': template_data})

def add(request, id):
    get_object_or_404(Movie, id=id)
    cart_selection = request.POST.get('cart_selection', '1')
    cart_name = f'cart_{cart_selection}'
    cart = request.session.get(cart_name, {})
    cart[id] = request.POST['quantity']
    request.session[cart_name] = cart

    # Set the active cart
    request.session['active_cart'] = cart_selection
    return redirect('cart.index')

def view_cart(request, cart_id):
    request.session['active_cart'] = str(cart_id)
    return redirect('cart.index')

def clear(request):
    active_cart_selection = request.session.get('active_cart', '1')
    cart_name = f'cart_{active_cart_selection}'
    request.session[cart_name] = {}
    return redirect('cart.index')

@login_required
def purchase(request):
    active_cart_selection = request.session.get('active_cart', '1')
    cart_name = f'cart_{active_cart_selection}'
    cart = request.session.get(cart_name, {})
    movie_ids = list(cart.keys())

    if (movie_ids == []):
        return redirect('cart.index')
    
    movies_in_cart = Movie.objects.filter(id__in=movie_ids)
    cart_total = calculate_cart_total(cart, movies_in_cart)

    order = Order()
    order.user = request.user
    order.total = cart_total
    order.save()

    for movie in movies_in_cart:
        item = Item()
        item.movie = movie
        item.price = movie.price
        item.order = order
        item.quantity = cart[str(movie.id)]
        item.save()

    request.session[cart_name] = {}
    template_data = {}
    template_data['title'] = 'Purchase confirmation'
    template_data['order_id'] = order.id
    return render(request, 'cart/purchase.html', {'template_data': template_data})

moviesstore/cart/templates/cart/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load cart_filters %}
<div class="p-3">
  <div class="container">
    <div class="row mt-3">
      <div class="col mx-auto mb-3">
        <h2>Shopping Cart - Cart {{ template_data.active_cart }}</h2>
        <hr />
        <div class="btn-group" role="group" aria-label="Select Cart">
          <a href="{% url 'cart.view' cart_id=1 %}" class="btn {% if template_data.active_cart == 1 %}btn-primary{% else %}btn-outline-primary{% endif %}">Cart 1</a>
          <a href="{% url 'cart.view' cart_id=2 %}" class="btn {% if template_data.active_cart == 2 %}btn-primary{% else %}btn-outline-primary{% endif %}">Cart 2</a>
          <a href="{% url 'cart.view' cart_id=3 %}" class="btn {% if template_data.active_cart == 3 %}btn-primary{% else %}btn-outline-primary{% endif %}">Cart 3</a>
        </div>
      </div>
    </div>
    <div class="row m-1">
      <table class="table table-bordered table-striped text-center">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
          </tr>
        </thead>
        <tbody>
          {% for movie in template_data.movies_in_cart %}
          <tr>
            <td>{{ movie.id }}</td>
            <td>{{ movie.name }}</td>
            <td>${{ movie.price }}</td>
            {% with active_cart_selection=request.session.active_cart|default:"1" %}
            {% with cart_name="cart_"|add:active_cart_selection %}
            {% with current_cart=request.session|get_item:cart_name %}
            <td>{{ current_cart|get_quantity:movie.id }}</td>
            {% endwith %}
            {% endwith %}
            {% endwith %}
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="row">
      <div class="text-end">
        <a class="btn btn-outline-secondary mb-2"><b>Total to pay:</b> ${{ template_data.cart_total }}</a>
        {% if template_data.movies_in_cart|length > 0 %}
        <a href="{% url 'cart.purchase' %}" class="btn bg-dark text-white mb-2">Purchase</a>
        <a href="{% url 'cart.clear' %}">
          <button class="btn btn-danger mb-2">
            Remove all movies from Cart
          </button>
        </a>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

moviesstore/cart/templates/cart/orders.html
{% extends 'base.html' %}
{% block content %}
<div class="p-3">
  <div class="container">
    <div class="row mt-3">
      <div class="col mx-auto mb-3">
        <h2>My Orders</h2>
        <hr />
        {% for order in template_data.orders %}
        <div class="card mb-4">
          <div class="card-header">
            Order #{{ order.id }}
          </div>
          <div class="card-body">
            <b>Date:</b> {{ order.date }}<br />
            <b>Total:</b> ${{ order.total }}<br />
            <table class="table table-bordered table-striped text-center mt-3">
              <thead>
                <tr>
                  <th scope="col">Item ID</th>
                  <th scope="col">Movie</th>
                  <th scope="col">Price</th>
                  <th scope="col">Quantity</th>
                </tr>
              </thead>
              <tbody>
                {% for item in order.item_set.all %}
                <tr>
                  <td>{{ item.movie.id }}</td>
                  <td>
                    <a class="link-dark" href="{% url 'movies.show' id=item.movie.id %}">                    
                      {{ item.movie.name }}
                    </a>
                  </td>
                  <td>${{ item.movie.price }}</td>
                  <td>{{ item.quantity }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

moviesstore/cart/templates/cart/purchase.html
{% extends 'base.html' %}
{% block content %}
<div class="p-3">
  <div class="container">
    <div class="row mt-3">
      <div class="col mx-auto mb-3">
        <h2>Purchase Completed</h2>
        <hr />
        <p>Congratulations, purchase completed. Order number is: <b>#{{ template_data.order_id }}</b></p>
      </div>
    </div>
  </div>
</div>
{% endblock content %}